[project]
name = "citycoin"
requirements = []

[repl.analysis]
costs_version = 2

# cities

[contracts.miamicoin-auth]
path = "contracts/cities/mia/local/miamicoin-auth.clar"
depends_on = ["citycoin-core-trait", "citycoin-token-trait"]

[contracts.miamicoin-core-v1]
path = "contracts/cities/mia/local/miamicoin-core-v1.clar"
depends_on = ["miamicoin-auth", "miamicoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.miamicoin-core-v2]
path = "contracts/cities/mia/local/miamicoin-core-v1.clar"
depends_on = ["miamicoin-auth", "miamicoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.miamicoin-core-v3]
path = "contracts/cities/mia/local/miamicoin-core-v1.clar"
depends_on = ["miamicoin-auth", "miamicoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.miamicoin-token]
path = "contracts/cities/mia/local/miamicoin-token.clar"
depends_on = ["sip-010-trait-ft-standard", "miamicoin-auth", "citycoin-token-trait"]

[contracts.miamicoin-token-v2]
path = "contracts/cities/mia/local/miamicoin-token-v2.clar"
depends_on = ["sip-010-trait-ft-standard", "miamicoin-auth", "citycoin-token-trait", "miamicoin-token"]

[contracts.newyorkcitycoin-auth]
path = "contracts/cities/nyc/local/newyorkcitycoin-auth.clar"
depends_on = ["citycoin-core-trait", "citycoin-token-trait"]

[contracts.newyorkcitycoin-core-v1]
path = "contracts/cities/nyc/local/newyorkcitycoin-core-v1.clar"
depends_on = ["newyorkcitycoin-auth", "newyorkcitycoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.newyorkcitycoin-core-v2]
path = "contracts/cities/nyc/local/newyorkcitycoin-core-v1.clar"
depends_on = ["newyorkcitycoin-auth", "newyorkcitycoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.newyorkcitycoin-core-v3]
path = "contracts/cities/nyc/local/newyorkcitycoin-core-v1.clar"
depends_on = ["newyorkcitycoin-auth", "newyorkcitycoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.newyorkcitycoin-token]
path = "contracts/cities/nyc/local/newyorkcitycoin-token.clar"
depends_on = ["sip-010-trait-ft-standard", "newyorkcitycoin-auth", "citycoin-token-trait"]

[contracts.newyorkcitycoin-token-v2]
path = "contracts/cities/nyc/local/newyorkcitycoin-token-v2.clar"
depends_on = ["sip-010-trait-ft-standard", "newyorkcitycoin-auth", "citycoin-token-trait", "newyorkcitycoin-token"]

# core

[contracts.citycoin-core-trait]
path = "contracts/core/local/citycoin-core-trait.clar"
depends_on = []

[contracts.citycoin-token-trait]
path = "contracts/core/local/citycoin-token-trait.clar"
depends_on = []

[contracts.citycoin-auth]
path = "contracts/core/local/citycoin-auth.clar"
depends_on = ["citycoin-core-trait", "citycoin-token-trait"]

[contracts.citycoin-token]
path = "contracts/core/local/citycoin-token.clar"
depends_on = ["sip-010-trait-ft-standard", "citycoin-auth", "citycoin-token-trait"]

[contracts.citycoin-core-v1]
path = "contracts/core/local/citycoin-core-v1.clar"
depends_on = ["citycoin-auth", "citycoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.citycoin-core-v2]
path = "contracts/core/local/citycoin-core-v2.clar"
depends_on = ["citycoin-auth", "citycoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.citycoin-core-v3]
path = "contracts/core/local/citycoin-core-v2.clar"
depends_on = ["citycoin-auth", "citycoin-token", "citycoin-vrf", "citycoin-core-trait"]

# tardis

[contracts.citycoin-tardis-v1]
path = "contracts/tardis/local/citycoin-tardis-v1.clar"
depends_on = ["citycoin-core-v1"]

[contracts.citycoin-tardis-v2]
path = "contracts/tardis/local/citycoin-tardis-v2.clar"
depends_on = ["citycoin-core-v1"]

# utilities

[contracts.sip-010-trait-ft-standard]
path = "contracts/utilities/local/sip-010-trait-ft-standard.clar"
depends_on = []

[contracts.test-utils]
path = "contracts/utilities/local/test-utils.clar"
depends_on = ["citycoin-core-v1"]

# vote

[contracts.citycoin-vote-v1]
path = "contracts/vote/local/citycoin-vote-v1.clar"
depends_on = ["citycoin-core-v1"]

# vrf

[contracts.citycoin-vrf]
path = "contracts/vrf/local/citycoin-vrf.clar"
depends_on = []
