# GitHub action to run Clarinet tests against the contracts
# and fail if code is invalid or a test fails.

name: Contract Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  # allow running manually
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Check contract syntax"
        uses: docker://hirosystems/clarinet:latest
        with:
          args: check
      - name: "Execute test suite"
        uses: docker://hirosystems/clarinet:latest
        with:
          args: test --coverage
      - name: "Upload code coverage"
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.lcov
